Refactor Usage of `<Flag />` Component
selsa-inube/design-system-web pull request #140
Opened 2024-07-05 21:52 UTC by cmarin001

This PR proposes changes to the usage of the `<Flag />` component within the codebase. The goal is to improve the component's integration and usage patterns to enhance maintainability and readability.

2024-07-30 02:07 UTC, wfercanas requested changes

2024-07-30 02:07 UTC, wfercanas commented on src/proposals/20240705-flag-component-enhancement.md
> +![carbon](https://github.com/selsa-inube/design-system-web/assets/45011420/1862208d-4ff7-4e42-bc7b-22ee7de9c969)
Instead of using images, use backticks to add the code in the markdown file.

2024-07-30 02:07 UTC, wfercanas commented on src/proposals/20240705-flag-component-enhancement.md
> +![image](https://github.com/selsa-inube/design-system-web/assets/45011420/50ee5cea-318e-43a6-93d2-5b863a9824fe)
Instead of using images, use the markdown extension in github to create diagrams with mermaid:
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams

2024-07-31 02:28 UTC, cmarin001 commented on src/proposals/20240705-flag-component-enhancement.md
solved

2024-07-31 02:50 UTC, cmarin001 commented on src/proposals/20240705-flag-component-enhancement.md
> +![carbon](https://github.com/selsa-inube/design-system-web/assets/45011420/1862208d-4ff7-4e42-bc7b-22ee7de9c969)
solved

2024-07-31 02:55 UTC, cmarin001 commented on src/proposals/20240705-flag-component-enhancement.md
> +![image](https://github.com/selsa-inube/design-system-web/assets/45011420/50ee5cea-318e-43a6-93d2-5b863a9824fe)
solved

2024-07-31 16:30 UTC, wfercanas requested changes

2024-07-31 16:30 UTC, wfercanas commented on proposals/20240705-flag-component-enhancement.md
> +  return context;
I think it would be better to publish with useFlag the array of flags and the methods to add and remove flags from that array.
This because:

1. The context is uniquely for usage inside the scope of the flags implementation, so we can make it private and offer through the hook just the operations we want to allow
2. By exporting the Provider and the hook at the end, we end up being aligned in terms of architecture with how we implemented some other tools like authentication, where we just export AuthProvider and useAuth.

2024-07-31 16:30 UTC, wfercanas commented on proposals/20240705-flag-component-enhancement.md
> +  const [messages, setMessages] = useState<FlagMessage[]>([]);
Don't name this `messages`, rename it to `flags` to keep it consistent.

2024-07-31 16:30 UTC, wfercanas commented on proposals/20240705-flag-component-enhancement.md
> +    const id = ++idCounter;
Use `crypto.randomUUID()` instead to create the `id`

2024-07-31 16:30 UTC, wfercanas commented on proposals/20240705-flag-component-enhancement.md
> +      <FlagPortal messages={messages} removeMessage={removeMessage} />
Don't pass flags and removeFlag through props:

1. Add flags in the value of the provider
2. Add removeFlag in the value of the provider.
3. Inside FlagsPortal, import useFlags() and get the flags with the hook.

2024-07-31 16:30 UTC, wfercanas commented on proposals/20240705-flag-component-enhancement.md
> +    setTimeout(() => removeMessage(id), message.duration);
We shouldn't control the removal of a flag solely with this setTimeout. Remember that the user can delay the closing of a flag with hovering the flag and seeing the countdown-bar stop.

2024-09-06 00:40 UTC, wfercanas approved these changes

2024-09-06 00:40 UTC, merged