Install inubekit-icon and replace all `<Icon />` components
selsa-inube/design-system-web pull request #71
Opened 2024-02-22 21:12 UTC by cmarin001

This pull request details the comprehensive integration of the `inubekit-icon` library into our application, alongside the systematic replacement of all existing `<Icon />` components with their counterparts from the newly adopted library. Aimed at streamlining icon management and ensuring visual consistency across the application, this update leverages the enhanced features and extensive icon set provided by `inubekit-icon`.

2024-02-22 23:06 UTC, JanuarAsprilla approved these changes

2024-02-23 15:32 UTC, wfercanas requested changes

2024-02-23 15:32 UTC, wfercanas commented on src/design-system/data/Icon/Playground/index.tsx
> +          appearance={dataChildren?.selectProps?.appearance!}
En esta línea persiste un error:

![image](https://github.com/selsa-inube/design-system-web/assets/36939686/d7a941a7-979c-4a18-9373-be3ebcdefc11)

2024-02-23 20:02 UTC, wfercanas approved these changes

2024-02-23 20:02 UTC, merged